defaults:
  - model: wav2vec2
  - dataset: librispeech
  - _self_

data:
  hidden_states_path: "features/${model.name}_${model.init_type}_${dataset.name}_hidden_states.npz"
  acoustic_targets_path: "features/${model.name}_${model.init_type}_${dataset.name}_targets.npz"

probing:
  probe_id: "ridge"
  alphas: [0.1, 1.0, 10.0]
  target_regression_features: ["mfcc", "stft", "mel"]
  target_classification_features: ["speaker_id"]
  layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]